### PR TITLE
#162397222 Chore: Refactor codes

### PR DESCRIPTION
**Pull request by Chrismarcel**
__What does this PR do?__
This refactor eliminates certain bad practices and also implements good practices as detailed during the feedback from the LFA. 

__Description of tasks__
- Implement JS Doc properly and add a return type for each JS Doc
- Every method should have a JS Doc describing what the method does
- Ensure conditional statements have braces, eliminate the one-liner conditionals
- Ensure that tests actually target the values, not the properties
- Remove all commented out codes
- End all files with a new line including HTML files.
- Improve test coverage score

__Link to relevant story__
[#162397222](https://www.pivotaltracker.com/story/show/162397222)

### CODE REVIEW

**Review by otseobande — COMMENTED** [review]
All your files should end with an empty line including `html` files.

**Comment by Chrismarcel** [comment]
Duly noted and feedback acknowledged. I'd implement this feedback and get back to you. Thank you.

**Comment by Chrismarcel** [comment]
I have implemented the feedback and also improved my test coverage results.

**Review by otseobande — APPROVED** [review]
I see that you have implemented most of the feedback given to you. Please note that you can also handle updating of fields with just one method as opposed to having a method for every field you want to update. Your error messages are a lot better now.

**Comment by Chrismarcel** [comment]
Thanks a lot for the feedback. I will refactor my code and get back to you.

**Pull request merged**
